# ----------------------------------------------------------------------------------------------------------------------
# Configuration data for synthetic data generation.
# ----------------------------------------------------------------------------------------------------------------------

project_name: "TrackForge"
seed: 42
